/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {

		System.out.println(" is text");

	}
    public boolean someLibraryMethod() {
        return true;
    }
}
